name: Verify dist
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main

jobs:
  verify-dist:
    name: Verify that 'dist' has been regenerated
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Clear gradle.properties
        run: rm -fv gradle.properties

      - name: Generate dist
        uses: gradle/gradle-build-action@v2
        with:
          arguments: package

      - name: Compare dist with repo
        run: |
          git diff --exit-code dist
