name: "Gradle Build"
on:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fix gradle.properties
        run: perl -lpe 'print unless /nodejs\.version/'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
